version: "3.8"
services:
  postgres-stalser-dev:
    image: postgres:14
    domainname: postgres_auth
    ports:
      - "15432:15432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stalser