version: "3.8"
services:
  postgres-stalser-dev:
    image: postgres:14
    domainname: postgres_auth
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stalser



#Пускай эта штука останется попробую разобраться потом
#  webserver:
#    image: nginx:alpine
#    container_name: webserver
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "80:80"
#      - "443:443"
#    networks:
#      - app-network
#networks:
#  app-network:
#    driver: bridge