### Запрос на создание юзера
POST http://localhost:8081/register
Content-Type: application/json

{
    "login": "grafwwwolf",
    "password": "grafpswd",
    "email": "grafwwwolf@mail.ru"
}

### Запрос на создание юзера
POST http://localhost:8081/register
Content-Type: application/json

{
  "login": "autotest_user",
  "password": "autotestpswd",
  "email": "autotest@mail.ru"
}