server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/stalser
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
logging:
  level:
    ru:
      gb: debug
stalser:
  api:
    version: 1
    url: api/v${stalser.api.version}
  invite:
    url: localhost:${server.port}/${stalser.api.url}
    email-address-from: "stalser.app@mail.ru"
jwt:
  access:
    secret: sdfsdfsef5hrjghjukl3kjol5rt653w4r3w43r54rty6tyui6675r54e6w454e52rtu4y13ty5u
    lifetime: 60 # в минутах
  refresh:
    secret: cx09v8fd09fsghds0fg9ds-0gsd0-g8sd-0gf9sd9gfs09fgsudfg0s-dfg7sdgfsd9gjudisjg
    lifetime: 30 # в днях
kafka:
  server: localhost:9092